[tool.black]
line-length = 100
extend-exclude = '''
(\{\{cookiecutter\.repo_name\}\}
|\.venv
|dist
|build
|\.mypy_cache
|\.pytest_cache
|\.ruff_cache
)
'''

[tool.ruff]
line-length = 100
target-version = "py312"
extend-exclude = [
  "{{cookiecutter.repo_name}}",
  ".venv",
  "dist",
  "build",
  ".mypy_cache",
  ".pytest_cache",
  ".ruff_cache",
]

[tool.mypy]
# keep mypy from walking into the cookiecutter skeleton
exclude = '(\{\{cookiecutter\.repo_name\}\}|\.venv|dist|build|\.mypy_cache|\.pytest_cache|\.ruff_cache)'
