[tool.black]
line-length = 100
# Black uses REGEX here. We must escape the {{ }}.
extend-exclude = '''
(\{\{cookiecutter\.repo_name\}\}
|\.venv
|dist
|build
|\.mypy_cache
|\.pytest_cache
|\.ruff_cache
)
'''

[tool.ruff]
# Ruff uses GLOB patterns here (NOT regex). List paths plainly.
line-length = 100
target-version = "py312"
extend-exclude = [
  "{{cookiecutter.repo_name}}",  # exclude the template skeleton
  ".venv",
  "dist",
  "build",
  ".mypy_cache",
  ".pytest_cache",
  ".ruff_cache",
]

[tool.mypy]
# Mypy uses REGEX here. This is fine as-is.
exclude = '(\{\{cookiecutter\.repo_name\}\}|\.venv|dist|build|\.mypy_cache|\.pytest_cache|\.ruff_cache)'
