[tool.black]
line-length = 100
# Black uses REGEX. Escape the braces so it ignores the skeleton.
extend-exclude = '''
(\{\{cookiecutter\.repo_name\}\}
|\.venv
|dist
|build
|\.mypy_cache
|\.pytest_cache
|\.ruff_cache
)
'''

[tool.ruff]
# Ruff uses GLOB patterns (not regex). Braces are special there.
# Use a substring glob instead of literal braces.
line-length = 100
target-version = "py312"
extend-exclude = [
  "**/*cookiecutter.repo_name*",  # safely ignores the skeleton folder
  ".venv",
  "dist",
  "build",
  ".mypy_cache",
  ".pytest_cache",
  ".ruff_cache",
]

[tool.mypy]
# mypy uses REGEX. Keep the escaped-brace regex (works fine).
exclude = '(\{\{cookiecutter\.repo_name\}\}|\.venv|dist|build|\.mypy_cache|\.pytest_cache|\.ruff_cache)'
