# .github/workflows/ci-linux.yml
name: CI (Linux)

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install tooling / deps
        run: |
          python -m pip install -U pip
          # If your template/project has dev extras, use them; otherwise bootstrap tools
          (pip install -e ".[dev]") || pip install pytest ruff black mypy

      - name: Lint (ruff)
        run: ruff check . --output-format=github

      - name: Format check (black)
        run: black --check .

      - name: Type check (mypy)  # won't fail template runs if types aren't set up yet
        run: mypy . || true

      - name: Test
        run: |
          if [ -f ./tasks.sh ]; then
            chmod +x ./tasks.sh
            ./tasks.sh test
          else
            pytest -q --maxfail=1 --disable-warnings
          fi
