name: CI (Windows)

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install pytest ruff

      - name: Lint
        run: |
          .\tasks.bat lint

      - name: Test
        run: |
          .\tasks.bat test
