# .github/workflows/ci-windows.yml
name: CI (Windows)

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install tooling / deps
        shell: bash
        run: |
          python -m pip install -U pip
          (pip install -e ".[dev]") || pip install pytest ruff black mypy

      - name: Lint
        run: .\tasks.bat lint

      - name: Test
        run: .\tasks.bat test
